dist: xenial
language: python
python:
- 3.7

cache:
  pip: true
  apt: true

before_install:
- openssl aes-256-cbc -K $encrypted_fe0b4cce96b5_key -iv $encrypted_fe0b4cce96b5_iv -in dpkg.priv.key.enc -d | gpg --import
- sudo apt-get install dpkg-sig fakeroot

script:
- apt-cache rdepends libdbus-glib-1-2 # make sure we still need this
- python3 -u build-repo
