dist: xenial
language: python
python:
- 3.7

before_install:
- openssl aes-256-cbc -K $encrypted_fe0b4cce96b5_key -iv $encrypted_fe0b4cce96b5_iv -in dpkg.priv.key.enc -d | gpg --import

script:
- ls -l
