[Zotero]
mimetype = "x-scheme-handler/zotero"

["Research Information Systems document"]
mimetype = [ "application/x-endnote-refer", "application/x-research-info-systems", "text/ris", "text/x-research-info-systems",]
extension = ".ris"
de = "Research Information Systems dokument"

["ISI Common Export Format document"]
mimetype = "application/x-inst-for-Scientific-info"
extension = ".isi"
de = "ISI Common Export Format dokument"

["Metadata Object Description Schema document"]
mimetype = "application/mods+xml"
extension = ".mods"
de = "Metadata Object Description Schema dokument"

["Resource Description Framework document"]
mimetype = "application/rdf+xml"
extension = ".rdf"
de = "Resource Description Framework dokument"

["BibTeX document"]
mimetype = [ "application/x-bibtex", "text/x-bibtex",]
extension = ".bib"
de = "BibTeX dokument"

["MAchine-Readable Cataloging (MARC) record"]
mimetype = "application/marc"
extension = [ ".mrc", ".marc",]
de = "MAchine-Readable Cataloging (MARC) aufzeichnung"

["CSL citation style"]
mimetype = "application/vnd.citationstyles.style+xml"
extension = ".csl"
de = "CSL zitatstil"
