name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ master, auto ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: install signing key
      run: gpg --batch --passphrase "${{ secrets.PASSPHRASE }}" --decrypt dpkg.priv.key.gpg | gpg --import
    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get update
        sudo apt-get install dpkg-sig fakeroot

#    - name: Cache built debs for next round
#      id: cache
#      uses: actions/cache@v2
#      env:
#        cache-name: v2
#      with:
#        path: |
#          ./repo
#        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('release') }}-${{ hashFiles('requirements.txt') }}
#        restore-keys: |
#          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Force rebuild on manual dispatch
      if: github.event_name == 'workflow_dispatch'
      run: echo "REBUILD=true" >> $GITHUB_ENV
    - name: refresh repo
      id: repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./release
    - run: echo rebuilt=${{ steps.repo.outputs.rebuilt }}
    - name: publish repo
      if: steps.repo.outputs.rebuilt == 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        tag: apt-get-test
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        overwrite: true
        file: repo/*
