name: Release Zotero/Juris-M .deb packages

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ master, gpg ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Import GPG key
      id: import_gpg
      uses: retorquere/ghaction-import-gpg@a2a66a7
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: install build requirements
      run: |
        sudo add-apt-repository ppa:mozillateam/ppa -y
        sudo apt-get update
        sudo apt-get install dpkg-sig fakeroot

    - name: Cache built debs for next round
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v2
      with:
        path: |
          ./repo
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('release') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('repo/Packages') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: refresh repo
      id: repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./release
    - run: |
        echo rebuilt=${{ steps.repo.outputs.rebuilt }}
        echo url=${{ steps.repo.outputs.url }}

    - name: Install repo
      if: steps.repo.outputs.rebuilt == 'true'
      run: |
        curl -sL ${{ steps.repo.outputs.url}}/install.sh | sudo bash
        sudo apt-get update

    - name: attempt install
      uses: nick-invision/retry@v2
      if: steps.repo.outputs.rebuilt == 'true'
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: sudo apt-get install zotero zotero-beta jurism jurism-beta
